// This is where the gameState is stored
//Because of each card location needs four items of data in it, I have chosen to make each card it's own object for readability.
const gameState = {
    card_1: {
        "cardObjectType": "green",
        "tileWord": "Art",
        "currentSide": "back",
        "flippedState": true,   
    },
    card_2: {
        "cardObjectType": "green",
        "tileWord": "Intention",
        "currentSide": "back",
        "flippedState": true, 
    },
    card_3: {
        "cardObjectType": "tan",
        "tileWord": "Orange",
        "currentSide": "back",
        "flippedState": true,
    },
    card_4: {
        "cardObjectType": "blue",
        "tileWord": "Cup",
        "currentSide": "back",
        "flippedState": true,
    },
    card_5: {
        "cardObjectType": "blue",
        "tileWord": "Cry",
        "currentSide": "back",
        "flippedState": true,
    },
    card_6: {
        "cardObjectType": "blue",
        "tileWord": "Walk",
        "currentSide": "back",
        "flippedState": true,
    },
    card_7: {
        "cardObjectType": "tan",
        "tileWord": "Assistance",
        "currentSide": "back",
        "flippedState": true,
    },
    card_8: {
        "cardObjectType": "blue",
        "tileWord": "Proposal",
        "currentSide": "back",
        "flippedState": true,
    },
    card_9: {
        "cardObjectType": "green",
        "tileWord": "Complaint",
        "currentSide": "back",
        "flippedState": true,
    },
    card_10: {
        "cardObjectType": "green",
        "tileWord": "Target",
        "currentSide": "back",
        "flippedState": true,
    },
    card_11: {"cardObjectType": "tan",
        "tileWord": "Background",
        "currentSide": "back",
        "flippedState": true,
    },
    card_12: {
        "cardObjectType": "green",
        "tileWord": "Structure",
        "currentSide": "back",
        "flippedState": true,
    },
    card_13: {
        "cardObjectType": "tan",
        "tileWord": "Implement",
        "currentSide": "back",
        "flippedState": true,
    },
    card_14: {"cardObjectType": "blue",
        "tileWord": "Education",
        "currentSide": "back",
        "flippedState": true,
    },
    card_15: {
        "cardObjectType": "green",
        "tileWord": "Steak",
        "currentSide": "back",
        "flippedState": true,
    },
    card_16: {
        "cardObjectType": "green",
        "tileWord": "Shape",
        "currentSide": "back",
        "flippedState": true,
    },
    card_17: {
        "cardObjectType": "green",
        "tileWord": "Drink",
        "currentSide": "back",
        "flippedState": true,
    },
    card_18: {
        "cardObjectType": "blue",
        "tileWord": "Person",
        "currentSide": "back",
        "flippedState": true,
    },
    card_19: {
        "cardObjectType": "green",
        "tileWord": "Child",
        "currentSide": "back",
        "flippedState": true,
    },
    card_20: {
        "cardObjectType": "blue",
        "tileWord": "Town",
        "currentSide": "back",
        "flippedState": true,
    },
    card_21: {
        "cardObjectType": "blue",
        "tileWord": "Wonder",
        "currentSide": "back",
        "flippedState": true,
    },
    card_22: {
        "cardObjectType": "tan",
        "tileWord": "Score",
        "currentSide": "back",
        "flippedState": true,
    },
    card_23: {
        "cardObjectType": "tan",
        "tileWord": "Big",
        "currentSide": "back",
        "flippedState": true,
    },
    card_24: {
        "cardObjectType": "black",
        "tileWord": "Frame",
        "currentSide": "back",
        "flippedState": true,
    },
    card_25: {
        "cardObjectType": "tan",
        "tileWord": "Card",
        "currentSide": "back",
        "flippedState": true,
    },
    otherInfo: {
        "startingTeam":"Blue",
        "currentTurn":"Green",
        "gameOver":false,
        "greenCardsLeft":3,
        "blueCardsLeft":5,
        "playerRole": "Captain",
        "showBackColorSide":true,
        "showClueInputControls":false,
    },
    blueTeamClueLog: {       
    },
    greenTeamClueLog: {
    },
}